//! Background task management for async command execution.
//! Manages background process lifecycle, output, and stuck detection.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio::sync::Notify;

use serde::{Deserialize, Serialize};
use thiserror::Error;
use tokio::process::Command;
use tokio::sync::{oneshot, Mutex};
use uuid::Uuid;

use crate::stuck_detect::{self, StuckDetectConfig};

pub(crate) type TaskMap = Arc<Mutex<HashMap<String, TaskHandle>>>;

/// Errors from the background task subsystem.
#[derive(Debug, Error)]
pub enum BackgroundTaskError {
    #[error("spawn failed: {0}")]
    SpawnFailed(String),
    #[error("task not found: {0}")]
    NotFound(String),
    #[error("task not running: {0}")]
    NotRunning(String),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

/// Lifecycle state of a background task.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TaskState {
    /// Process is running.
    Running { is_backgrounded: bool },
    /// Process exited successfully.
    Completed { exit_code: i32 },
    /// Process exited with a non-zero exit code.
    Failed { exit_code: i32 },
    /// Process was killed externally.
    Killed,
}

/// A handle to a background task.
#[derive(Debug, Clone)]
pub struct BackgroundTask {
    pub id: String,
    pub command: String,
    pub state: TaskState,
    pub output_path: PathBuf,
}

/// Notification delivery priority.
///
/// Variant declaration order determines the derived `Ord` ordering:
/// `Now > Next > Later`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum NotificationPriority {
    /// Inject at a convenient later point.
    Later,
    /// Inject into the next dialogue turn immediately.
    Next,
    /// Highest priority — inject immediately (before user input).
    /// Used for system-level urgent notifications.
    Now,
}

/// A pending completion notification generated by the manager.
#[derive(Debug, Clone)]
pub struct CompletionNotification {
    /// Identifier of the completed task.
    pub task_id: String,
    /// Original command.
    pub command: String,
    /// Final task state.
    pub state: TaskState,
    /// Path to the task output file.
    pub output_path: PathBuf,
    /// Delivery priority.
    pub priority: NotificationPriority,
    /// Human-readable summary for the notification.
    pub summary: String,
    /// Optional suggestion for the user based on the task result.
    pub suggestion: Option<String>,
}

/// Internal handle for per-task bookkeeping.
pub(crate) struct TaskHandle {
    pub(crate) id: String,
    pub(crate) command: String,
    pub(crate) state: TaskState,
    pub(crate) output_path: PathBuf,
    pub(crate) session_id: String,
    pub(crate) kill_tx: Option<oneshot::Sender<()>>,
    pub(crate) notified: bool,
    /// Wall-clock time when the task was created.
    pub(crate) created_at: tokio::time::Instant,
    /// Shared notifier set by the timeout monitor to trigger kill.
    pub(crate) timeout_notify: Arc<Notify>,
}

// ---------------------------------------------------------------------------
// Manager
// ---------------------------------------------------------------------------

/// Manages the full lifecycle of background tasks.
pub struct BackgroundTaskManager {
    tasks: TaskMap,
    pub(crate) temp_dir: PathBuf,
    notifications: Arc<Mutex<Vec<CompletionNotification>>>,
    /// Maximum total execution time in seconds per task.
    /// Tasks exceeding this limit are force-killed.
    pub(crate) max_execution_secs: u64,
}

impl Default for BackgroundTaskManager {
    fn default() -> Self {
        Self {
            tasks: Arc::new(Mutex::new(HashMap::new())),
            temp_dir: PathBuf::from("/tmp"),
            notifications: Arc::new(Mutex::new(Vec::new())),
            max_execution_secs: 1800,
        }
    }
}

impl BackgroundTaskManager {
    /// Create a new manager using the default temp root (`/tmp`).
    pub fn new() -> Self {
        Self::with_temp_dir("/tmp")
    }

    /// Create a new manager with an explicit temp root directory.
    pub fn with_temp_dir(temp_dir: impl Into<PathBuf>) -> Self {
        Self {
            tasks: Arc::new(Mutex::new(HashMap::new())),
            temp_dir: temp_dir.into(),
            notifications: Arc::new(Mutex::new(Vec::new())),
            max_execution_secs: 1800,
        }
    }

    /// Create a new manager with a custom total execution time limit.
    ///
    /// `max_execution_secs` is the maximum total time (seconds) a task
    /// may run before being force-killed. Must be greater than the
    /// timeout parameter cap (600 s / 10 min).
    pub fn with_max_execution_secs(temp_dir: impl Into<PathBuf>, max_execution_secs: u64) -> Self {
        Self {
            tasks: Arc::new(Mutex::new(HashMap::new())),
            temp_dir: temp_dir.into(),
            notifications: Arc::new(Mutex::new(Vec::new())),
            max_execution_secs,
        }
    }
}

impl BackgroundTaskManager {
    /// Spawn a shell command in the background, returning immediately.
    pub async fn spawn(
        &self,
        command: &str,
        cwd: &Path,
        is_backgrounded: bool,
        session_id: &str,
    ) -> Result<BackgroundTask, BackgroundTaskError> {
        let task_id = Uuid::new_v4().to_string();
        let output_path = prepare_task_dir(&self.temp_dir, &task_id).await?;

        insert_initial_handle(
            &self.tasks,
            &task_id,
            command,
            &output_path,
            is_backgrounded,
            session_id,
        )
        .await;

        tracing::info!(
            task_id = %task_id,
            command = %command,
            "background task started"
        );

        stuck_detect::start_stuck_detection(
            task_id.clone(),
            output_path.clone(),
            command.to_owned(),
            Arc::clone(&self.tasks),
            Arc::clone(&self.notifications),
            StuckDetectConfig::default(),
        );

        let timeout_notify = {
            let map = lock_map(&self.tasks).await;
            map.get(&task_id)
                .map(|h| Arc::clone(&h.timeout_notify))
                .expect("handle must exist after insert")
        };

        let shared = Arc::clone(&self.tasks);
        let cmd = command.to_owned();
        let cwd = cwd.to_path_buf();
        let out = output_path.clone();
        let tid = task_id.clone();

        let notifs = Arc::clone(&self.notifications);
        let tn = Arc::clone(&timeout_notify);

        tokio::spawn(async move {
            run_shell_command(&cmd, &cwd, &out, &shared, &tid, &notifs, &tn).await;
        });

        // Spawn the total-execution-time-limit monitor.
        let max_secs = self.max_execution_secs;
        let tid = task_id.clone();
        let shared = Arc::clone(&self.tasks);
        let notifs = Arc::clone(&self.notifications);
        tokio::spawn(async move {
            spawn_max_execution_monitor(max_secs, &tid, &shared, &notifs).await;
        });

        Ok(make_public_task(
            &task_id,
            command,
            &output_path,
            is_backgrounded,
        ))
    }

    /// Take over a running child process.
    pub async fn backgroundize(
        &self,
        mut child: tokio::process::Child,
        command: &str,
        is_backgrounded: bool,
        session_id: &str,
    ) -> Result<BackgroundTask, BackgroundTaskError> {
        let task_id = Uuid::new_v4().to_string();
        let output_path = prepare_task_dir(&self.temp_dir, &task_id).await?;

        let stdout = child.stdout.take();
        let stderr = child.stderr.take();

        insert_initial_handle(
            &self.tasks,
            &task_id,
            command,
            &output_path,
            is_backgrounded,
            session_id,
        )
        .await;

        tracing::info!(
            task_id = %task_id,
            command = %command,
            "background task started"
        );

        stuck_detect::start_stuck_detection(
            task_id.clone(),
            output_path.clone(),
            command.to_owned(),
            Arc::clone(&self.tasks),
            Arc::clone(&self.notifications),
            StuckDetectConfig::default(),
        );

        let timeout_notify = {
            let map = lock_map(&self.tasks).await;
            map.get(&task_id)
                .map(|h| Arc::clone(&h.timeout_notify))
                .expect("handle must exist after insert")
        };

        let shared = Arc::clone(&self.tasks);
        let out = output_path.clone();
        let tid = task_id.clone();

        let notifs = Arc::clone(&self.notifications);
        let tn = Arc::clone(&timeout_notify);

        tokio::spawn(async move {
            backgroundize_process(child, stdout, stderr, &out, &shared, &tid, &notifs, &tn).await;
        });

        // Spawn the total-execution-time-limit monitor.
        let max_secs = self.max_execution_secs;
        let tid = task_id.clone();
        let shared = Arc::clone(&self.tasks);
        let notifs = Arc::clone(&self.notifications);
        tokio::spawn(async move {
            spawn_max_execution_monitor(max_secs, &tid, &shared, &notifs).await;
        });

        Ok(make_public_task(
            &task_id,
            command,
            &output_path,
            is_backgrounded,
        ))
    }
}

impl BackgroundTaskManager {
    /// Send SIGKILL to a running task, transitioning to Killed.
    pub async fn kill(&self, task_id: &str) -> Result<(), BackgroundTaskError> {
        let mut map = lock_map(&self.tasks).await;
        let handle = map
            .get_mut(task_id)
            .ok_or_else(|| BackgroundTaskError::NotFound(task_id.to_owned()))?;

        if !matches!(handle.state, TaskState::Running { .. }) {
            return Err(BackgroundTaskError::NotRunning(task_id.to_owned()));
        }

        if let Some(kill_tx) = handle.kill_tx.take() {
            let _ = kill_tx.send(());
        }
        handle.state = TaskState::Killed;
        tracing::info!(task_id = %task_id, "background task killed");
        Ok(())
    }

    /// Return `true` if the task is in the [`TaskState::Running`] state.
    pub async fn is_running(&self, task_id: &str) -> bool {
        let map = lock_map(&self.tasks).await;
        map.get(task_id)
            .is_some_and(|h| matches!(h.state, TaskState::Running { .. }))
    }

    /// Retrieve a snapshot of the current task state.
    pub async fn get_task(&self, task_id: &str) -> Option<BackgroundTask> {
        let map = lock_map(&self.tasks).await;
        map.get(task_id).map(|h| BackgroundTask {
            id: h.id.clone(),
            command: h.command.clone(),
            state: h.state.clone(),
            output_path: h.output_path.clone(),
        })
    }

    /// Mark a task as notified (dedup support for Step 1.3).
    pub async fn mark_notified(&self, task_id: &str) {
        let mut map = lock_map(&self.tasks).await;
        if let Some(h) = map.get_mut(task_id) {
            h.notified = true;
        }
    }

    /// Drain pending notifications without re-delivery.
    pub async fn pending_notifications(&self) -> Vec<CompletionNotification> {
        let mut n = self.notifications.lock().await;
        std::mem::take(&mut *n)
    }

    /// Remove output directories and handles for finished tasks.
    ///
    /// - [`TaskState::Completed`] and [`TaskState::Failed`]: output
    ///   directory is removed and the handle is evicted from the map.
    /// - [`TaskState::Killed`]: the handle is evicted but the output
    ///   directory is preserved so the caller can inspect what was
    ///   written before the kill.
    ///
    /// I/O errors are logged but do not propagate — this method never
    /// panics.
    pub async fn cleanup_finished(&self) {
        let mut map = lock_map(&self.tasks).await;
        let finished: Vec<String> = map
            .iter()
            .filter(|(_, h)| {
                matches!(
                    h.state,
                    TaskState::Completed { .. } | TaskState::Failed { .. } | TaskState::Killed
                )
            })
            .map(|(id, _)| id.clone())
            .collect();

        for task_id in &finished {
            if let Some(handle) = map.get(task_id) {
                // Preserve output directories for killed tasks — the caller
                // should be able to inspect what was written before the kill.
                if handle.state != TaskState::Killed {
                    let parent = handle.output_path.parent();
                    if let Some(dir) = parent {
                        if let Err(e) = tokio::fs::remove_dir_all(dir).await {
                            tracing::warn!(
                                task_id = %task_id,
                                path = %dir.display(),
                                error = %e,
                                "failed to remove task output directory"
                            );
                        }
                    }
                }
            }
            map.remove(task_id);
        }
    }
    /// Remove output directories and handles for ALL terminal tasks
    /// belonging to the given session.
    /// Unlike [`cleanup_finished`](Self::cleanup_finished), this also
    /// removes output for [`TaskState::Killed`] tasks.  Used during
    /// session purge to reclaim all output files for that session.
    pub async fn cleanup_all_finished(&self, session_id: &str) {
        let mut map = lock_map(&self.tasks).await;
        let finished: Vec<String> = map
            .iter()
            .filter(|(_, h)| {
                h.session_id == session_id
                    && matches!(
                        h.state,
                        TaskState::Completed { .. } | TaskState::Failed { .. } | TaskState::Killed
                    )
            })
            .map(|(id, _)| id.clone())
            .collect();

        for task_id in &finished {
            if let Some(handle) = map.get(task_id) {
                let parent = handle.output_path.parent();
                if let Some(dir) = parent {
                    if let Err(e) = tokio::fs::remove_dir_all(dir).await {
                        tracing::warn!(
                            task_id = %task_id,
                            path = %dir.display(),
                            error = %e,
                            "failed to remove task output directory"
                        );
                    }
                }
            }
            map.remove(task_id);
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// TaskManager — bridge to closeclaw_common trait
// ═══════════════════════════════════════════════════════════════════════════

#[async_trait::async_trait]
impl crate::TaskManager for BackgroundTaskManager {
    async fn spawn_task(
        &self,
        command: &str,
        cwd: &std::path::Path,
        is_backgrounded: bool,
        session_id: &str,
    ) -> Result<BackgroundTask, BackgroundTaskError> {
        self.spawn(command, cwd, is_backgrounded, session_id).await
    }

    async fn backgroundize_task(
        &self,
        child: tokio::process::Child,
        command: &str,
        is_backgrounded: bool,
        session_id: &str,
    ) -> Result<BackgroundTask, BackgroundTaskError> {
        self.backgroundize(child, command, is_backgrounded, session_id)
            .await
    }

    async fn kill_task(&self, task_id: &str) -> Result<(), BackgroundTaskError> {
        self.kill(task_id).await
    }

    async fn get_task(&self, task_id: &str) -> Option<BackgroundTask> {
        self.get_task(task_id).await
    }

    async fn list_running_tasks(&self) -> Vec<crate::task_manager::RunningTaskInfo> {
        let map = lock_map(&self.tasks).await;
        map.values()
            .filter(|h| matches!(h.state, TaskState::Running { .. }))
            .map(|h| crate::task_manager::RunningTaskInfo {
                task_id: h.id.clone(),
                command: h.command.clone(),
                elapsed_secs: h.created_at.elapsed().as_secs(),
            })
            .collect()
    }

    async fn drain_notifications(&self) -> Vec<CompletionNotification> {
        let mut notifications = self.pending_notifications().await;
        // Sort by priority descending: Now > Next > Later
        notifications.sort_by_key(|b| std::cmp::Reverse(b.priority));
        notifications
    }

    async fn cleanup_finished(&self) {
        self.cleanup_finished().await
    }

    async fn cleanup_all_finished(&self, session_id: &str) {
        self.cleanup_all_finished(session_id).await
    }
}

// ---------------------------------------------------------------------------
// Process execution helpers
// ---------------------------------------------------------------------------

async fn run_shell_command(
    command: &str,
    cwd: &Path,
    output_path: &Path,
    tasks: &TaskMap,
    task_id: &str,
    notifications: &Arc<Mutex<Vec<CompletionNotification>>>,
    timeout_notify: &Arc<Notify>,
) {
    let result = Command::new("sh")
        .arg("-c")
        .arg(command)
        .current_dir(cwd)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn();

    match result {
        Ok(child) => {
            run_background_child(
                child,
                output_path,
                tasks,
                task_id,
                notifications,
                timeout_notify,
            )
            .await;
        }
        Err(e) => {
            mark_task_failed(tasks, task_id, &e).await;
        }
    }
}

async fn run_background_child(
    mut child: tokio::process::Child,
    output_path: &Path,
    tasks: &TaskMap,
    task_id: &str,
    notifications: &Arc<Mutex<Vec<CompletionNotification>>>,
    timeout_notify: &Arc<Notify>,
) {
    let stdout = child.stdout.take();
    let stderr = child.stderr.take();
    let (kill_tx, kill_rx) = oneshot::channel();

    {
        let mut map = lock_map(tasks).await;
        if let Some(h) = map.get_mut(task_id) {
            h.kill_tx = Some(kill_tx);
        }
    }

    let exit_code =
        await_process(child, stdout, stderr, output_path, kill_rx, timeout_notify).await;

    finalize_state(tasks, task_id, exit_code, notifications).await;
}

async fn mark_task_failed(tasks: &TaskMap, task_id: &str, error: &std::io::Error) {
    let mut map = lock_map(tasks).await;
    if let Some(h) = map.get_mut(task_id) {
        h.state = TaskState::Failed { exit_code: 1 };
        tracing::error!(
            task_id = %task_id,
            error = %error,
            "failed to spawn background command"
        );
    }
}

async fn backgroundize_process(
    child: tokio::process::Child,
    stdout: Option<tokio::process::ChildStdout>,
    stderr: Option<tokio::process::ChildStderr>,
    output_path: &Path,
    tasks: &TaskMap,
    task_id: &str,
    notifications: &Arc<Mutex<Vec<CompletionNotification>>>,
    timeout_notify: &Arc<Notify>,
) {
    let (kill_tx, kill_rx) = oneshot::channel();
    {
        let mut map = lock_map(tasks).await;
        if let Some(h) = map.get_mut(task_id) {
            h.kill_tx = Some(kill_tx);
        }
    }

    let exit_code =
        await_process(child, stdout, stderr, output_path, kill_rx, timeout_notify).await;

    finalize_state(tasks, task_id, exit_code, notifications).await;
}

async fn await_process(
    mut child: tokio::process::Child,
    stdout: Option<tokio::process::ChildStdout>,
    stderr: Option<tokio::process::ChildStderr>,
    output_path: &Path,
    kill_rx: oneshot::Receiver<()>,
    timeout_notify: &Arc<Notify>,
) -> i32 {
    let file = tokio::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(output_path)
        .await;

    let file = match file {
        Ok(f) => f,
        Err(e) => {
            tracing::error!(
                task_id = "process",
                error = %e,
                "failed to open output file"
            );
            return 1;
        }
    };

    let stdout_file = file.try_clone().await.expect("cloning output file handle");
    let stdout_handle = tokio::spawn(copy_reader(stdout, stdout_file));
    let stderr_handle = tokio::spawn(copy_reader(stderr, file));

    let code = tokio::select! {
        result = child.wait() => {
            result.map(|s| s.code().unwrap_or(1)).unwrap_or(1)
        }
        _ = kill_rx => {
            let _ = child.kill().await;
            -1
        }
        _ = timeout_notify.notified() => {
            let _ = child.kill().await;
            -1
        }
    };

    let _ = stdout_handle.await;
    let _ = stderr_handle.await;
    code
}

async fn copy_reader<R: tokio::io::AsyncRead + Unpin>(
    mut reader: Option<R>,
    mut file: tokio::fs::File,
) {
    if let Some(ref mut r) = reader {
        let _ = tokio::io::copy(r, &mut file).await;
    }
}

// ---------------------------------------------------------------------------
// Total-execution-time-limit monitor
// ---------------------------------------------------------------------------

/// Monitors a task and force-kills it when `max_secs` elapses.
///
/// The notifier is shared with [`await_process`] which awaits it in its
/// `select!` and kills the child when notified.
///
/// An info-level log and a completion notification are emitted when
/// the task is killed by this monitor.
async fn spawn_max_execution_monitor(
    max_secs: u64,
    task_id: &str,
    tasks: &TaskMap,
    notifications: &Arc<Mutex<Vec<CompletionNotification>>>,
) {
    let deadline = std::time::Duration::from_secs(max_secs);
    tokio::time::sleep(deadline).await;

    // Check if the task is still running and trigger kill via the flag.
    let (_notify, command, output_path) = {
        let mut map = lock_map(tasks).await;
        if let Some(h) = map.get_mut(task_id) {
            if !matches!(h.state, TaskState::Running { .. }) {
                return; // Task already finished.
            }
            h.state = TaskState::Killed;
            h.timeout_notify.notify_one();
            if let Some(kill_tx) = h.kill_tx.take() {
                let _ = kill_tx.send(());
            }
            (
                Arc::clone(&h.timeout_notify),
                h.command.clone(),
                h.output_path.clone(),
            )
        } else {
            return; // Task already cleaned up.
        }
    };

    tracing::info!(
        task_id = %task_id,
        command = %command,
        max_execution_secs = max_secs,
        "background task killed: total execution time limit reached"
    );

    let notif = CompletionNotification {
        task_id: task_id.to_owned(),
        command: command.clone(),
        state: TaskState::Killed,
        output_path,
        priority: NotificationPriority::Later,
        summary: format!(
            "Background command '{}' killed: total execution time limit ({}s) reached",
            command, max_secs
        ),
        suggestion: Some(format!(
            "The command exceeded the total execution time limit of {}s. \
             Consider breaking it into smaller tasks or increasing the limit.",
            max_secs
        )),
    };
    notifications.lock().await.push(notif);
}

async fn finalize_state(
    tasks: &TaskMap,
    task_id: &str,
    exit_code: i32,
    notifications: &Arc<Mutex<Vec<CompletionNotification>>>,
) {
    let mut map = lock_map(tasks).await;
    if let Some(h) = map.get_mut(task_id) {
        // Do not overwrite an explicit Kill.
        if h.state == TaskState::Killed {
            return;
        }
        let new_state = if exit_code == 0 {
            TaskState::Completed { exit_code }
        } else {
            TaskState::Failed { exit_code }
        };
        h.state = new_state.clone();
        tracing::info!(
            task_id = %task_id,
            command = %h.command,
            state = ?new_state,
            "background task reached terminal state"
        );
        // Dedup: if a stuck alert was already sent, skip completion
        // notification — the task only notifies once.
        if h.notified {
            return;
        }
        h.notified = true;
        let summary = match &new_state {
            TaskState::Completed { .. } => {
                format!("Background command '{}' completed", h.command)
            }
            TaskState::Failed { exit_code } => {
                format!(
                    "Background command '{}' failed (exit code {})",
                    h.command, exit_code
                )
            }
            TaskState::Killed | TaskState::Running { .. } => {
                unreachable!("only Completed or Failed at this point")
            }
        };
        let notif = CompletionNotification {
            task_id: h.id.clone(),
            command: h.command.clone(),
            state: new_state,
            output_path: h.output_path.clone(),
            priority: NotificationPriority::Later,
            summary,
            suggestion: None,
        };
        notifications.lock().await.push(notif);
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

async fn lock_map(tasks: &TaskMap) -> tokio::sync::MutexGuard<'_, HashMap<String, TaskHandle>> {
    tasks.lock().await
}

async fn prepare_task_dir(temp_dir: &Path, task_id: &str) -> Result<PathBuf, BackgroundTaskError> {
    let dir = temp_dir.join("closeclaw/background").join(task_id);

    tokio::fs::create_dir_all(&dir)
        .await
        .map_err(BackgroundTaskError::Io)?;

    Ok(dir.join("output"))
}

async fn insert_initial_handle(
    tasks: &TaskMap,
    task_id: &str,
    command: &str,
    output_path: &Path,
    is_backgrounded: bool,
    session_id: &str,
) {
    let handle = TaskHandle {
        id: task_id.to_owned(),
        command: command.to_owned(),
        state: TaskState::Running { is_backgrounded },
        output_path: output_path.to_path_buf(),
        session_id: session_id.to_owned(),
        kill_tx: None,
        notified: false,
        created_at: tokio::time::Instant::now(),
        timeout_notify: Arc::new(Notify::new()),
    };
    let mut map = lock_map(tasks).await;
    map.insert(task_id.to_owned(), handle);
}

fn make_public_task(
    task_id: &str,
    command: &str,
    output_path: &Path,
    is_backgrounded: bool,
) -> BackgroundTask {
    BackgroundTask {
        id: task_id.to_owned(),
        command: command.to_owned(),
        state: TaskState::Running { is_backgrounded },
        output_path: output_path.to_path_buf(),
    }
}

#[cfg(test)]
#[path = "background_tests.rs"]
mod tests;

#[cfg(test)]
#[path = "cleanup_finished_tests.rs"]
mod cleanup_finished_tests;

#[cfg(test)]
#[path = "list_running_tasks_tests.rs"]
mod list_running_tasks_tests;
