//! Background task management for async command execution.
//! Manages background process lifecycle, output, and stuck detection.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use thiserror::Error;
use tokio::process::Command;
use tokio::sync::{oneshot, Mutex};
use uuid::Uuid;

use super::stuck_detect::{self, StuckDetectConfig};

pub(crate) type TaskMap = Arc<Mutex<HashMap<String, TaskHandle>>>;

/// Errors from the background task subsystem.
#[derive(Debug, Error)]
pub enum BackgroundTaskError {
    #[error("spawn failed: {0}")]
    SpawnFailed(String),
    #[error("task not found: {0}")]
    NotFound(String),
    #[error("task not running: {0}")]
    NotRunning(String),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

/// Lifecycle state of a background task.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TaskState {
    /// Process is running.
    Running,
    /// Process exited successfully.
    Completed { exit_code: i32 },
    /// Process exited with a non-zero exit code.
    Failed { exit_code: i32 },
    /// Process was killed externally.
    Killed,
}

/// A handle to a background task.
#[derive(Debug, Clone)]
pub struct BackgroundTask {
    pub id: String,
    pub command: String,
    pub state: TaskState,
    pub output_path: PathBuf,
}

/// Notification delivery priority.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NotificationPriority {
    /// Inject into the next dialogue turn immediately.
    Next,
    /// Inject at a convenient later point.
    Later,
}

/// A pending completion notification generated by the manager.
#[derive(Debug, Clone)]
pub struct CompletionNotification {
    /// Identifier of the completed task.
    pub task_id: String,
    /// Original command.
    pub command: String,
    /// Final task state.
    pub state: TaskState,
    /// Path to the task output file.
    pub output_path: PathBuf,
    /// Delivery priority.
    pub priority: NotificationPriority,
}

/// Internal handle for per-task bookkeeping.
pub(crate) struct TaskHandle {
    pub(crate) id: String,
    pub(crate) command: String,
    pub(crate) state: TaskState,
    pub(crate) output_path: PathBuf,
    pub(crate) kill_tx: Option<oneshot::Sender<()>>,
    pub(crate) notified: bool,
}

// ---------------------------------------------------------------------------
// Manager
// ---------------------------------------------------------------------------

/// Manages the full lifecycle of background tasks.
pub struct BackgroundTaskManager {
    tasks: TaskMap,
    temp_dir: PathBuf,
    notifications: Arc<Mutex<Vec<CompletionNotification>>>,
}

impl Default for BackgroundTaskManager {
    fn default() -> Self {
        Self::new()
    }
}

impl BackgroundTaskManager {
    /// Create a new manager using the default temp root (`/tmp`).
    pub fn new() -> Self {
        Self::with_temp_dir("/tmp")
    }

    /// Create a new manager with an explicit temp root directory.
    pub fn with_temp_dir(temp_dir: impl Into<PathBuf>) -> Self {
        Self {
            tasks: Arc::new(Mutex::new(HashMap::new())),
            temp_dir: temp_dir.into(),
            notifications: Arc::new(Mutex::new(Vec::new())),
        }
    }
}

impl BackgroundTaskManager {
    /// Spawn a shell command in the background, returning immediately.
    pub async fn spawn(
        &self,
        command: &str,
        cwd: &Path,
    ) -> Result<BackgroundTask, BackgroundTaskError> {
        let task_id = Uuid::new_v4().to_string();
        let output_path = prepare_task_dir(&self.temp_dir, &task_id).await?;

        insert_initial_handle(&self.tasks, &task_id, command, &output_path).await;

        stuck_detect::start_stuck_detection(
            task_id.clone(),
            output_path.clone(),
            command.to_owned(),
            Arc::clone(&self.tasks),
            Arc::clone(&self.notifications),
            StuckDetectConfig::default(),
        );

        let shared = Arc::clone(&self.tasks);
        let cmd = command.to_owned();
        let cwd = cwd.to_path_buf();
        let out = output_path.clone();
        let tid = task_id.clone();

        let notifs = Arc::clone(&self.notifications);

        tokio::spawn(async move {
            run_shell_command(&cmd, &cwd, &out, &shared, &tid, &notifs).await;
        });

        Ok(make_public_task(&task_id, command, &output_path))
    }

    /// Take over a running child process.
    pub async fn backgroundize(
        &self,
        mut child: tokio::process::Child,
        command: &str,
        _cwd: &Path,
    ) -> Result<BackgroundTask, BackgroundTaskError> {
        let task_id = Uuid::new_v4().to_string();
        let output_path = prepare_task_dir(&self.temp_dir, &task_id).await?;

        let stdout = child.stdout.take();
        let stderr = child.stderr.take();

        insert_initial_handle(&self.tasks, &task_id, command, &output_path).await;

        stuck_detect::start_stuck_detection(
            task_id.clone(),
            output_path.clone(),
            command.to_owned(),
            Arc::clone(&self.tasks),
            Arc::clone(&self.notifications),
            StuckDetectConfig::default(),
        );

        let shared = Arc::clone(&self.tasks);
        let out = output_path.clone();
        let tid = task_id.clone();

        let notifs = Arc::clone(&self.notifications);

        tokio::spawn(async move {
            backgroundize_process(child, stdout, stderr, &out, &shared, &tid, &notifs).await;
        });

        Ok(make_public_task(&task_id, command, &output_path))
    }
}

impl BackgroundTaskManager {
    /// Send SIGKILL to a running task, transitioning to Killed.
    pub async fn kill(&self, task_id: &str) -> Result<(), BackgroundTaskError> {
        let mut map = lock_map(&self.tasks).await;
        let handle = map
            .get_mut(task_id)
            .ok_or_else(|| BackgroundTaskError::NotFound(task_id.to_owned()))?;

        if handle.state != TaskState::Running {
            return Err(BackgroundTaskError::NotRunning(task_id.to_owned()));
        }

        if let Some(kill_tx) = handle.kill_tx.take() {
            let _ = kill_tx.send(());
        }
        handle.state = TaskState::Killed;
        Ok(())
    }

    /// Return `true` if the task is in the [`TaskState::Running`] state.
    pub async fn is_running(&self, task_id: &str) -> bool {
        let map = lock_map(&self.tasks).await;
        map.get(task_id)
            .is_some_and(|h| h.state == TaskState::Running)
    }

    /// Retrieve a snapshot of the current task state.
    pub async fn get_task(&self, task_id: &str) -> Option<BackgroundTask> {
        let map = lock_map(&self.tasks).await;
        map.get(task_id).map(|h| BackgroundTask {
            id: h.id.clone(),
            command: h.command.clone(),
            state: h.state.clone(),
            output_path: h.output_path.clone(),
        })
    }

    /// Mark a task as notified (dedup support for Step 1.3).
    pub async fn mark_notified(&self, task_id: &str) {
        let mut map = lock_map(&self.tasks).await;
        if let Some(h) = map.get_mut(task_id) {
            h.notified = true;
        }
    }

    /// Drain pending notifications without re-delivery.
    pub async fn pending_notifications(&self) -> Vec<CompletionNotification> {
        let mut n = self.notifications.lock().await;
        std::mem::take(&mut *n)
    }
}

// ---------------------------------------------------------------------------
// Process execution helpers
// ---------------------------------------------------------------------------

async fn run_shell_command(
    command: &str,
    cwd: &Path,
    output_path: &Path,
    tasks: &TaskMap,
    task_id: &str,
    notifications: &Arc<Mutex<Vec<CompletionNotification>>>,
) {
    let result = Command::new("sh")
        .arg("-c")
        .arg(command)
        .current_dir(cwd)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn();

    match result {
        Ok(child) => {
            run_background_child(child, output_path, tasks, task_id, notifications).await;
        }
        Err(e) => {
            mark_task_failed(tasks, task_id, &e).await;
        }
    }
}

async fn run_background_child(
    mut child: tokio::process::Child,
    output_path: &Path,
    tasks: &TaskMap,
    task_id: &str,
    notifications: &Arc<Mutex<Vec<CompletionNotification>>>,
) {
    let stdout = child.stdout.take();
    let stderr = child.stderr.take();
    let (kill_tx, kill_rx) = oneshot::channel();

    {
        let mut map = lock_map(tasks).await;
        if let Some(h) = map.get_mut(task_id) {
            h.kill_tx = Some(kill_tx);
        }
    }

    let exit_code = await_process(child, stdout, stderr, output_path, kill_rx).await;

    finalize_state(tasks, task_id, exit_code, notifications).await;
}

async fn mark_task_failed(tasks: &TaskMap, task_id: &str, error: &std::io::Error) {
    let mut map = lock_map(tasks).await;
    if let Some(h) = map.get_mut(task_id) {
        h.state = TaskState::Failed { exit_code: 1 };
        tracing::error!(
            task_id = %task_id,
            error = %error,
            "failed to spawn background command"
        );
    }
}

async fn backgroundize_process(
    child: tokio::process::Child,
    stdout: Option<tokio::process::ChildStdout>,
    stderr: Option<tokio::process::ChildStderr>,
    output_path: &Path,
    tasks: &TaskMap,
    task_id: &str,
    notifications: &Arc<Mutex<Vec<CompletionNotification>>>,
) {
    let (kill_tx, kill_rx) = oneshot::channel();
    {
        let mut map = lock_map(tasks).await;
        if let Some(h) = map.get_mut(task_id) {
            h.kill_tx = Some(kill_tx);
        }
    }

    let exit_code = await_process(child, stdout, stderr, output_path, kill_rx).await;

    finalize_state(tasks, task_id, exit_code, notifications).await;
}

async fn await_process(
    mut child: tokio::process::Child,
    stdout: Option<tokio::process::ChildStdout>,
    stderr: Option<tokio::process::ChildStderr>,
    output_path: &Path,
    kill_rx: oneshot::Receiver<()>,
) -> i32 {
    let file = tokio::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(output_path)
        .await;

    let file = match file {
        Ok(f) => f,
        Err(e) => {
            tracing::error!(
                task_id = "process",
                error = %e,
                "failed to open output file"
            );
            return 1;
        }
    };

    let stdout_file = file.try_clone().await.expect("cloning output file handle");
    let stdout_handle = tokio::spawn(copy_reader(stdout, stdout_file));
    let stderr_handle = tokio::spawn(copy_reader(stderr, file));

    let code = tokio::select! {
        result = child.wait() => {
            result.map(|s| s.code().unwrap_or(1)).unwrap_or(1)
        }
        _ = kill_rx => {
            let _ = child.kill().await;
            -1
        }
    };

    let _ = stdout_handle.await;
    let _ = stderr_handle.await;
    code
}

async fn copy_reader<R: tokio::io::AsyncRead + Unpin>(
    mut reader: Option<R>,
    mut file: tokio::fs::File,
) {
    if let Some(ref mut r) = reader {
        let _ = tokio::io::copy(r, &mut file).await;
    }
}

async fn finalize_state(
    tasks: &TaskMap,
    task_id: &str,
    exit_code: i32,
    notifications: &Arc<Mutex<Vec<CompletionNotification>>>,
) {
    let mut map = lock_map(tasks).await;
    if let Some(h) = map.get_mut(task_id) {
        // Do not overwrite an explicit Kill.
        if h.state == TaskState::Killed {
            return;
        }
        let new_state = if exit_code == 0 {
            TaskState::Completed { exit_code }
        } else {
            TaskState::Failed { exit_code }
        };
        let notif = CompletionNotification {
            task_id: h.id.clone(),
            command: h.command.clone(),
            state: new_state.clone(),
            output_path: h.output_path.clone(),
            priority: NotificationPriority::Later,
        };
        h.state = new_state;
        notifications.lock().await.push(notif);
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

async fn lock_map(tasks: &TaskMap) -> tokio::sync::MutexGuard<'_, HashMap<String, TaskHandle>> {
    tasks.lock().await
}

async fn prepare_task_dir(temp_dir: &Path, task_id: &str) -> Result<PathBuf, BackgroundTaskError> {
    let dir = temp_dir.join("closeclaw/background").join(task_id);

    tokio::fs::create_dir_all(&dir)
        .await
        .map_err(BackgroundTaskError::Io)?;

    Ok(dir.join("output"))
}

async fn insert_initial_handle(tasks: &TaskMap, task_id: &str, command: &str, output_path: &Path) {
    let handle = TaskHandle {
        id: task_id.to_owned(),
        command: command.to_owned(),
        state: TaskState::Running,
        output_path: output_path.to_path_buf(),
        kill_tx: None,
        notified: false,
    };
    let mut map = lock_map(tasks).await;
    map.insert(task_id.to_owned(), handle);
}

fn make_public_task(task_id: &str, command: &str, output_path: &Path) -> BackgroundTask {
    BackgroundTask {
        id: task_id.to_owned(),
        command: command.to_owned(),
        state: TaskState::Running,
        output_path: output_path.to_path_buf(),
    }
}

#[cfg(test)]
#[path = "background_tests.rs"]
mod tests;
