//! Shared payloads of the background task subsystem.
//!
//! Carried by the [`TaskManager`](crate::TaskManager) trait contract:
//! task handles, lifecycle states, completion notifications and their
//! delivery priority. Definitions live here so that consumers can talk
//! about background tasks without depending on `closeclaw-tasks`.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Errors from the background task subsystem.
#[derive(Debug, Error)]
pub enum BackgroundTaskError {
    #[error("spawn failed: {0}")]
    SpawnFailed(String),
    #[error("task not found: {0}")]
    NotFound(String),
    #[error("task not running: {0}")]
    NotRunning(String),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

/// Lifecycle state of a background task.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TaskState {
    /// Process is running.
    Running { is_backgrounded: bool },
    /// Process exited successfully.
    Completed { exit_code: i32 },
    /// Process exited with a non-zero exit code.
    Failed { exit_code: i32 },
    /// Process was killed externally.
    Killed,
}

/// A handle to a background task.
#[derive(Debug, Clone)]
pub struct BackgroundTask {
    pub id: String,
    pub command: String,
    pub state: TaskState,
    pub output_path: PathBuf,
}

/// Notification delivery priority.
///
/// Variant declaration order determines the derived `Ord` ordering:
/// `Now > Next > Later`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum NotificationPriority {
    /// Inject at a convenient later point.
    Later,
    /// Inject into the next dialogue turn immediately.
    Next,
    /// Highest priority — inject immediately (before user input).
    /// Used for system-level urgent notifications.
    Now,
}

/// A pending completion notification generated by the manager.
#[derive(Debug, Clone)]
pub struct CompletionNotification {
    /// Identifier of the completed task.
    pub task_id: String,
    /// Original command.
    pub command: String,
    /// Final task state.
    pub state: TaskState,
    /// Path to the task output file.
    pub output_path: PathBuf,
    /// Delivery priority.
    pub priority: NotificationPriority,
    /// Human-readable summary for the notification.
    pub summary: String,
    /// Optional suggestion for the user based on the task result.
    pub suggestion: Option<String>,
}

/// Lightweight summary of a currently running background task.
///
/// Returned by [`TaskManager::list_running_tasks`](crate::TaskManager::list_running_tasks) so the
/// caller can inject a running-task digest without querying individual tasks.
#[derive(Debug, Clone)]
pub struct RunningTaskInfo {
    /// Unique identifier of the background task.
    pub task_id: String,
    /// The original shell command.
    pub command: String,
    /// Seconds elapsed since the task was created.
    pub elapsed_secs: u64,
}
